### ISSUE TITLE
How can I use the model to predict a single sentence?

### ISSUE THREAD

**Issue by temco** [TVect/ChinNER#3]
After I finish training a model with the bin/run_bert.sh, how can I use the output-files to predict a single sentence? Is there a predict.py or predict function provided in this package? thanks

**Comment by TVect** [comment]
Not yet.
I will try to add this feature as soon as possible.

**Comment by TVect** [comment]
I have upload `models/bert_ner/client.py`. It may helps.
You may need to rerun `run_bert.sh` to get a saved model.

**Comment by temco** [comment]
OK, thanks for your help

**Comment by temco** [comment]
```
File "/Users/xumi/Downloads/ChinNER-/models/bert_ner/model.py", line 3
ModuleNotFoundError: No module named 'tf_metrics'
```
when I delete this line : `import tf_metrics`, the training is going on. It seems this line is a mistake, isn't it?

**Comment by TVect** [comment]
The model will use `tf_metrics` to calculate precision score, f1-score, etc. when running in EVAL mode.

You can install the package by running the following command:
```
pip install git+https://github.com/guillaumegenthial/tf_metrics.git
```

**Comment by temco** [comment]
thank you for your support
when I finished the training and ran `python -m models.bert_ner.client` at
the root directory, an error was caught as:
```

Traceback (most recent call last):

  File "/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)

  File "/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code

    exec(code, run_globals)

  File "/Users/xumi/Downloads/ChinNER-/models/bert_ner/client.py", line 45,
in <module>

    data_processor = DataProcessor.load_from_file(options.processor_file)

  File "/Users/xumi/Downloads/ChinNER-/models/bert_ner/data_helper.py",
line 30, in load_from_file

    with open(config_file) as fr:

TypeError: expected str, bytes or os.PathLike object, not NoneType

```

and what should I do?

TVect <notifications@github.com> 于2019年6月25日周二 上午9:58写道：

**Comment by TVect** [comment]
You should specify the `model_path` and `processor_file`: 

```
python -m models.bert_ner.client -m ./models/bert_ner/output/1560850786 -p ./models/bert_ner/output/data_processor.json
```

**Comment by temco** [comment]
OK, thank you, I've made it due to your command

TVect <notifications@github.com> 于2019年6月26日周三 下午3:03写道：
